/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author dattran
 */
public class FontChooserView extends javax.swing.JDialog {

    public JButton getBtnCancel() {
        return btnCancel;
    }

    public void setBtnCancel(JButton btnCancel) {
        this.btnCancel = btnCancel;
    }

    public JButton getBtnOK() {
        return btnOK;
    }

    public void setBtnOK(JButton btnOK) {
        this.btnOK = btnOK;
    }

    public JLabel getLblSampleText() {
        return lblSampleText;
    }

    public void setLblSampleText(JLabel lblSampleText) {
        this.lblSampleText = lblSampleText;
    }

    public JList<String> getLstFontSizes() {
        return lstFontSizes;
    }

    public void setLstFontSizes(JList<String> lstFontSizes) {
        this.lstFontSizes = lstFontSizes;
    }

    public JList<String> getLstFontStyles() {
        return lstFontStyles;
    }

    public void setLstFontStyles(JList<String> lstFontStyles) {
        this.lstFontStyles = lstFontStyles;
    }

    public JList<String> getLstFonts() {
        return lstFonts;
    }

    public void setLstFonts(JList<String> lstFonts) {
        this.lstFonts = lstFonts;
    }

    public JPanel getPnlSample() {
        return pnlSample;
    }

    public void setPnlSample(JPanel pnlSample) {
        this.pnlSample = pnlSample;
    }

    public JTextField getTxfFont() {
        return txfFont;
    }

    public void setTxfFont(JTextField txfFont) {
        this.txfFont = txfFont;
    }

    public JTextField getTxfFontSize() {
        return txfFontSize;
    }

    public void setTxfFontSize(JTextField txfFontSize) {
        this.txfFontSize = txfFontSize;
    }

    public JTextField getTxfFontStyle() {
        return txfFontStyle;
    }

    public void setTxfFontStyle(JTextField txfFontStyle) {
        this.txfFontStyle = txfFontStyle;
    }

    public FontChooserView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFont = new javax.swing.JLabel();
        lblFontStyle = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstFonts = new javax.swing.JList<>();
        txfFont = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstFontStyles = new javax.swing.JList<>();
        txfFontStyle = new javax.swing.JTextField();
        txfFontSize = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstFontSizes = new javax.swing.JList<>();
        pnlSample = new javax.swing.JPanel();
        lblSampleText = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Font Chooser");
        setResizable(false);

        lblFont.setText("Font:");

        lblFontStyle.setText("Font style:");

        lblSize.setText("Size:");

        jScrollPane3.setViewportView(lstFonts);

        jScrollPane4.setViewportView(lstFontStyles);

        jScrollPane5.setViewportView(lstFontSizes);

        pnlSample.setBorder(javax.swing.BorderFactory.createTitledBorder("Sample"));

        lblSampleText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSampleText.setText("AaBbYyZz");

        javax.swing.GroupLayout pnlSampleLayout = new javax.swing.GroupLayout(pnlSample);
        pnlSample.setLayout(pnlSampleLayout);
        pnlSampleLayout.setHorizontalGroup(
            pnlSampleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSampleLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblSampleText, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        pnlSampleLayout.setVerticalGroup(
            pnlSampleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSampleLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblSampleText)
                .addGap(26, 26, 26))
        );

        btnOK.setText("OK");

        btnCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFont)
                    .addComponent(txfFont)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pnlSample, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFontStyle)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txfFontStyle, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOK)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSize)
                    .addComponent(txfFontSize)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFont)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfFont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfFontStyle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFontStyle)
                        .addComponent(lblSize)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane3))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnOK)
                        .addComponent(btnCancel))
                    .addComponent(pnlSample, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblFont;
    private javax.swing.JLabel lblFontStyle;
    private javax.swing.JLabel lblSampleText;
    private javax.swing.JLabel lblSize;
    private javax.swing.JList<String> lstFontSizes;
    private javax.swing.JList<String> lstFontStyles;
    private javax.swing.JList<String> lstFonts;
    private javax.swing.JPanel pnlSample;
    private javax.swing.JTextField txfFont;
    private javax.swing.JTextField txfFontSize;
    private javax.swing.JTextField txfFontStyle;
    // End of variables declaration//GEN-END:variables
}
